@base_url = http://localhost:3003/api/v1

@access_token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDE5NzIzMzgsImlhdCI6MTc0MTk2NTEzOCwibmJmIjoxNzQxOTY1MTM4LCJzdWIiOiJiMDFkNjUzYS05YjRhLTQ3YWEtOTk3Zi04YWY4YWJlMDY3MzEifQ.BYJSsltvWEKchMh5uNeZrSUgLfkw8WfLCoHfsC9qwMDlr7yMjddyGKV9nCeeGwy-gj4a9KH-WDrmPyhtv_O13g

@user_id = b01d653a-9b4a-47aa-997f-8af8abe06731
@email = john.doe@test.com
@password = 00000000

# ================ User ================

# Get user token
POST {{base_url}}/token
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

# ================ Users ================

# Creation user
POST {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "{{email}}",
  "password": "{{password}}",
  "lastname": "Doe",
  "firstname": "John"
}

###

# Get user by ID
GET {{base_url}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

###

# Get all users
GET {{base_url}}/users?page=1&size=10
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Get all users deleted
GET {{base_url}}/users/deleted?page=1&size=10
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
