openapi: '3.0.2'
info:
  title: Go Clean API
  version: '1.0'
  description: REST API for Go using Clean Architecture
  contact:
    name: Fabien Bellanger
    email: valentil@gmail.com
  license:
    name: MIT
    url: https://github.com/fabienbellanger/go-clean-api/blob/main/LICENSE

servers:
  - url: http://localhost:{port}/api/v1
    description: Local server
    variables:
      port:
        enum:
          - "3003"
        default: "3003"
  - url: https://<base URL>/api/v1
    description: Production server

paths:
  /token:
    post:
      description: Authenticate a user
      tags:
        - "User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAccessTokenRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccessTokenResponse'
        '400':
            $ref: "#/components/responses/BadRequest"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '500':
            $ref: "#/components/responses/InternalServerError"

  /users:
    post:
      summary: ""
      description: User creation
      tags:
        - "Users"
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreationResponse'
        '400':
          $ref: "#/components/responses/BadRequest"
        '401':
          $ref: "#/components/responses/Unauthorized"
        '500':
          $ref: "#/components/responses/InternalServerError"
    
    get:
      summary: ""
      description: Get users
      tags:
        - "Users"
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          required: false
          description: Page number
          example: 1
        - in: query
          name: size
          schema:
            type: integer
            maximum: 100
          required: false
          description: Number of users per page
          example: 10
        # - in: query
        #   name: s
        #   schema:
        #     type: string
        #   required: false
        #   description: "Sort (Ex.: s=+lastname,-firstname) {+: ASC, -: DESC}"
        #   example: +lastname,+created_at
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
        '400':
            $ref: "#/components/responses/BadRequest"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '404':
            $ref: "#/components/responses/NotFound"
        '500':
            $ref: "#/components/responses/InternalServerError"
  
  /users/deleted:
    get:
      summary: ""
      description: Get deleted users
      tags:
        - "Users"
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          required: false
          description: Page number
          example: 1
        - in: query
          name: size
          schema:
            type: integer
            maximum: 100
          required: false
          description: Number of users per page
          example: 10
        # - in: query
        #   name: s
        #   schema:
        #     type: string
        #   required: false
        #   description: "Sort (Ex.: s=+lastname,-firstname) {+: ASC, -: DESC}"
        #   example: +lastname,+created_at
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
        '400':
            $ref: "#/components/responses/BadRequest"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '404':
            $ref: "#/components/responses/NotFound"
        '500':
            $ref: "#/components/responses/InternalServerError"

  /users/{id}:
    get:
      summary: ""
      description: Get user by ID
      tags:
        - "Users"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: User ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
            $ref: "#/components/responses/BadRequest"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '404':
            $ref: "#/components/responses/NotFound"
        '500':
            $ref: "#/components/responses/InternalServerError"
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Unauthorized:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
    BadRequest:
      description: Invalid parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
        text/plain:
          schema:
            type: string
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
    MethodNotAllowed:
      description: Method Not Allowed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
  schemas:
    ResponseError:
      type: object
      properties:
        code:
          type: integer
          minimum: 100
          maximum: 527
        message:
          type: string
      required:
        - code
        - message
    PaginationRequest:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
      required:
        - page
        - size
        - total
    GetAccessTokenRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
      example:
        email: john.doe@test.com
        password: "00000000"
      required:
        - email
        - password
    GetAccessTokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: Access token
        access_token_expired_at:
          type: string
          format: date-time
          description: Access token expiration date time
      required:
        - access_token
        - access_token_expired_at
    UserCreationRequest:
      type: object
      properties:
        lastname:
          type: string
        firstname:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
      required:
        - lastname
        - firstname
        - username
        - password
    UserCreationResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        lastname:
          type: string
        firstname:
          type: string
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - lastname
        - firstname
        - email
        - created_at
        - updated_at
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        lastname:
          type: string
        firstname:
          type: string
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
      required:
        - id
        - lastname
        - firstname
        - email
        - created_at
        - updated_at
    GetUsersResponse:
      allOf:
        - $ref: "#/components/schemas/PaginationRequest"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/UserResponse"
          required:
            - data